/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsConfig = {
  aws_project_region: 'us-east-1', //TO CHANGE
  aws_cognito_region: 'us-east-1', //TO CHANGE
  aws_user_pools_id: 'us-east-1_hv7GdCcZc', //TO CHANGE
  aws_user_pools_web_client_id: '5egm4ign62v00g356vtb9akeic', //TO CHANGE

  oauth: {
    domain: 'projects-userpool.auth.us-east-1.amazoncognito.com', //TO CHANGE
    scope: ['phone', 'email', 'openid', 'profile', 'aws.cognito.signin.user.admin'],
    redirectSignIn: 'http://localhost:3000',
    redirectSignOut: 'http://localhost:3000/login',
    responseType: 'code',
  },
};

export default awsConfig;
